<?
  function create_metatag ($title, $description, $keywords, $author, $index, $follow) {
    switch ($index) {
    case 1:
      $index = 'index';
      break;
    case 2:
      $index='';
      break;
    
    default:
      $index = '';
      break;
    }
    switch ($follow) {
      case 1:
        $follow = 'follow';
        break;
      case 2:
        $follow='';
        break;
      
      default:
        $follow = '';
        break;
    }
    if ($index != '' && $follow != '') {
      $meta_robot = $index . ', ' . $follow;
    }
    elseif ($index != '') {
      $meta_robot = $index;
    }
    else {
      $meta_robot = $follow;
    }
    $resultat = '<head>
  <title>'.$title.'</title>
  <meta name="description" content="'.$description.'" />
  <meta name="keywords" content="'.$keywords.'" />
  <meta name="author" content="'.$author.'"
  <meta name="robots" content="'.$meta_robot.'" />
  <!-- META Tags generated by http://www.submitexpress.com/meta-tags-generator.php -->
</head>';
  return $resultat;
  }

	extract($_POST);
  // Verification of the captcha here ...
  $response=file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=6LeLTSQUAAAAACX4j177jA6L6Nl5aPraDvyvzuSq&response=".$captcha_response."&remoteip=".$_SERVER['REMOTE_ADDR']);
  if($response==false)
  {
    echo 'You are a robot!';
  }else
  {
    // Send information for newsletter ect.
    //TODO
    echo create_metatag($title, $description, $keywords, $author, $index, $follow); 
  }    

	/*
	require_once('recaptcha/recaptchalib.php');
	$privatekey = "6LeLTSQUAAAAACX4j177jA6L6Nl5aPraDvyvzuSq";
	$resp = recaptcha_check_answer ($privatekey,
	                            $_SERVER["REMOTE_ADDR"],
	                            $_POST["recaptcha_challenge_field"],
	                            $_POST["recaptcha_response_field"]);

	if (!$resp->is_valid) {
	// What happens when the CAPTCHA was entered incorrectly
	die ("The reCAPTCHA wasn't entered correctly. Go back and try it again." .
	     "(reCAPTCHA said: " . $resp->error . ")");
	} else {
	// Your code here to handle a successful verification
		echo "ok";
	}
	*/
?>